config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get '/trails' => 'pages#index'
  get '/trails/trailinfo' => 'pages#show'

  get '/about' => 'pages#about'
  get '/help' => 'pages#help'
  get '/contact' => 'pages#contact'
  get '/blog' => 'pages#blog'
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, uniqueness: { case_sensitive: false },
                    presence: true, length: {maximum: 30},
                    format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true, length: {maximum: 15}
  validates :password, length: { minimum: 6}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  require "addressable/uri"
  def welcome
  end

  def index

    if params[:location] && params[:location] != ''
      @geocode = Geocoder.coordinates(params[:location])
      @lat = @geocode[0]
      @lon = @geocode[1]
    end

    if params[:activity]
      if @lat && @lon
        @response = HTTParty.get(endpoint + "&q[activities_activity_type_name_cont]=#{params[:activity]}&lat=#{@lat}&lon=#{@lon}")
      else
        @response = HTTParty.get(endpoint + "&q[activities_activity_type_name_cont]=#{params[:activity]}")
      end
      @coordinates = []
      @response["places"].each do |place|
        @coordinates << [place["lat"],place["lon"]]
      end

    elsif params[:activity] == ''
      if @lat && @lon
        @response = HTTParty.get(endpoint + "&lat=#{@lat}&lon=#{@lon}")
      else
        @response = HTTParty.get(endpoint)
      end

      @coordinates = []
      @response["places"].each do |place|
        @coordinates << [place["lat"],place["lon"]]
      end
    end

  end
  # container method
  def show
    if params[:trail]
        trail = params[:trail]
        name = trail.delete(' /')
        # weather not working yet
        # also need new trail get request
        encoded_url = URI.encode(endpoint + "&q[name_eq]=#{trail}")
        trailuri = HTTParty.get(encoded_url)
        @trail = JSON.parse(trailuri.body)
        @lat = @trail["places"][0]["lat"]
        @lon = @trail["places"][0]["lon"]

      # searchuri = HTTParty.get "http://api.openweathermap.org/data/2.5/forecast/daily?lat=#{@lat}&lon=#{@lon}&units=imperial&cnt=5&mode=json"
      # @responses = JSON.parse(searchuri.body)
      # @name = @responses['city']['name']
      @instagram = Instagram.tag_recent_media("#{name}", {:count => 3})
      # @tweets = $client.search("##{name}" + " -rt", result_type: "recent").take(3)
    else
    end
  # we need to take lat and lon from show location and save as varialble named lat lon
  # we need to remove whitespace from trail name and save as a variable named name
  # weather endpoint
        # searchuri = HTTParty.get "http://api.openweathermap.org/data/2.5/forecast/daily?lat=#{@lat}&lon=#{@lon}&units=imperial&cnt=5&mode=json"
        # @responses = JSON.parse(searchuri.body)
 
  # tweet and instagram endpoints
      # @tweets = $client.search("##{name}" + " -rt", result_type: "recent").take(3)
      #  @instagram = Instagram.tag_recent_media("#{name}", {:count => 4})
  end

  private

  def endpoint
    endpoint = "https://outdoor-data-api.herokuapp.com/api.json?api_key=4146c148c3d63d322c2b88b4870a6ba1"
  end

  def about

  end

  def contact

  end

  def help
  
  end

  def blog

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>TrailMix</title>
	<%= stylesheet_link_tag	'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	

<%= yield %>

<!--Hidden, this is used to grab the lon and lat of a location for google maps-->
<% if @trail %>
	<div id="latlon" lat=<%= @trail["places"][0]["lat"] %> lon=<%= @trail["places"][0]["lon"] %>></div>
<% end %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/pages/_footer.html.erb
<div class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<p>&copy Trail Mix</p>
				</div>
			</div>
		</div>
	</div>

app/views/pages/_nav.html.erb
<div class="header">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<ul>
			              <li><%= link_to "About", about_path %></li>
			              <li><%= link_to "Blog", blog_path %></li>
			        </ul>
				</div>
				<div class="col-md-4 text-center">
					<h1><%= link_to "Trail Mix", root_path %></h1>
				</div>
				<div class="col-md-4">
					<ul class='pull-right'>
			              <li ><%= link_to "Contact", contact_path %></li>
			              <li><%= link_to "Help", help_path %></li>
			        </ul>
				</div>
	    	</div>
    	</div>
   	</div>

app/views/pages/about.html.erb
<div class="static">
		<%= render 'nav' %>
		<div class="container">
			<div class="section">
				<h1>About Us</h1>

				<h2 >Who We Are</h2>

					<p>TrailMix is an application about you as much as it is about nature. It's about getting away and bringing things back to basics.</p>

					<p>Life can become frantic and hectic at times, but </p>

					<p>We're here to instill an appreciation of the natural world to people everywhere, because at the heart of it all, we too are creatures of our environment</p>

				<h2>How To Use Our Site</h2>
					<p>Simply city or area of your choosing and we find the closest, and most popular trails close to that area. Whether it be for mountain biking, hiking, snow sports, or just a simple stroll, we've got you covered.</p>

					<p>Once the search is made, the results are displayed and when you click the details of those results, Instagram Tags associated with the trail pop up to show you others who have trekked along the same path. </p>

					<p>Google Maps & weather will also display to kindly give you directions and show the forecast before embarking on your activity.</p>



				<h2>Our Team</h2>
					<ul>
						<li><h3>Calvin Liu</h3></li>
						<li><h3>Steven Gordon</h3></li>
						<li><h3>Jeryl Barnum</h3></li>
					</ul>
			</div>

			<%= render 'footer' %>

	</div>
</div>
        

app/views/pages/blog.html.erb
<div class="static">
		<%= render 'nav' %>
		<div class="container">
			<div class="section">
				<h1>Blog coming soon....</h1>

		
			</div>

			<%= render 'footer' %>

	</div>
</div>
        

app/views/pages/help.html.erb
<div class="static">
		<%= render 'nav' %>
		<div class="container">
			<div class="section">
				<h1>Help & FAQ</h1>
					<h2>How do I use your site?</h2>
						<p>Simple, just click search</p>

					<h2>Why don't I just use Yelp</h2>
						<p>Sure, why don't you?</p>

					<h2>Is your service free?</h2>
						<p>100%, but you're welcome to donate</p>
			</div>

			<%= render 'footer' %>

	</div>
</div>
        

app/views/pages/index.html.erb
<div class="jumbotron_index special">
    <!-- Video Background -->
    <video autoplay loop poster="54.183.64.164/raw-media/first-frame-screencap" id="video-background" muted>
    <source src="https://0.s3.envato.com/h264-video-previews/1eb3dc2e-48f5-4543-ae5a-59c4deaf34dd/11474096.mp4" type="video/mp4">
    </video> 

<%= render 'nav' %>
</div>
    <h1 class="title"><strong>Trails List<strong></h1>
<div id="columns">
    <% if @response %>
            <% @response["places"].each do |places| %>
                <div class="pin">
                    <div class="panel-heading"><h1><%= "#{places["city"]}, #{places["state"]}" %></h1></div>
                        <% places["activities"].each do |activity| %>
                            <div class="panel-body">  
                                
                                 <h2><%= activity["name"] %></h2>
                                 <p><strong>Activity: </strong><%= activity["activity_type_name"] %></p>
                                  <p><strong>Description: </strong><%= activity["description"] %></p>
                                  
                                
                                <div class="btn-group">
                                <%= link_to "Details", trail: "#{activity['name']}", action: "show" %>
                                </div>
                            </div>

                        <% end %>
                </div>
            <% end %>
        </div>
    <% end %>
</div>


 

app/views/pages/show.html.erb
<div class="static">
    <%= render 'nav' %>
    <div class="main">
            <% unless @trail.nil? %>
                <div class="row">
                    <div class ="col-xs-12 text-center">
                        <h1 class='place_name'><%= @trail['places'][0]['name'] %></h1>
                    </div>
                    <div class ="col-xs-12">
                        <div class="img_container text-center">
                            <% unless @instagram.nil? %>
                                <% @instagram.each_with_index do |instagram, index| %>
                                        <%= image_tag instagram.images.standard_resolution.url, :size => "260x180" %>

                                <% end %>
                            <% end %>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class ="col-xs-6">
                        <div class="place_body">
                            <h2><%= @trail['places'][0]['city'] %>, <%= @trail['places'][0]['state'] %></h2>
                                <p><strong>Activity Description:</strong> <%= @trail['places'][0]['activities'][0]['description'] %></p>
                                <p><strong>Description:</strong> <%= @trail['places'][0]['description'] %></p>
                            </div>
                    </div>
                    <div class="col-xs-4 text-center" > 
                        <h1>Directions</h1>
                            <div id="map-canvas"></div>
                    </div>
                </div>
            <% end %>
    </div>

            <%= render 'footer' %>
</div>  

app/views/pages/welcome.html.erb
<div class="static">
	<div class="container">
	<%= render "nav" %> <!-- rendering nav --> 
		<div class="container-fluid" id="section2">
	   		<div class="row">
	   			<div class="col-md-12 text-center">
	   			 	<%= image_tag "http://i.imgur.com/UItAvIi.png", :id => "style_image" %>
	   			</div>
	   			 <div class="col-md-12 text-center">
					<%= form_tag trails_path, method: 'get', class: 'form-inline' do %>
						<div class="form-group">  <!--Ends Search Field-->
							<%= text_field_tag :location, nil, placeholder: 'Type an address, city, or zip code.', size: 33, class: 'form-control' %>
						</div> 
						<div class="form-group">  <!--Drop down menu for search-->
							<%= select_tag "activity", "
								<option value=''>Select an Activity</option>
								<option>hiking</option>
								<option>camping</option>
								<option>mountain biking</option>
								<option>caving</option>
								<option>snow sports</option>

								".html_safe, class: 'form-control' %>
						</div>
						<div class="form-group">
							<%= submit_tag "Search", class: "btn btn-default" %>
						</div>
					<% end %>
						<br>
							<p id="quote"></p>  <!--Random Quotes created by JavaScript-->
				</div>  <!--Ends Col-md-12-->

			</div>  <!--Endss Row-->
		</div>  <!--Section 2-->	

	<%= render 'footer' %>
	</div> <!--Ends Class Container-->
</div> <!--Ends Static-->